### ISSUE TITLE
Binaries from `v0.4.0` being blocked on Windows and GitHub Actions runners

### ISSUE THREAD

**Issue by stevehipwell** [yshavit/mdq#276]
After the new `v0.4.0` release I can't run the binary locally on my corporate Windows machine nor can I run it on my GitHub Actions runner ([ref](https://github.com/stevehipwell/helm-charts/actions/runs/14080158815/job/39431049992?pr=1157)). I get that these two things might be unrelated, but it does seem like a coincidence.

**Comment by yshavit** [comment]
Can you clarify whether this is the Windows binary `mdq.exe`, or is it the Linux one being run under WSL?

I was also unable to run the `mdq.exe` binary locally, due to Windows Defender thinking it's a Trojan. Microsoft's site to submit files for false positives is down, so I'm not really sure what to do about this. :-(

**Comment by yshavit** [comment]
Ah, it looks like it's back up (https://www.microsoft.com/en-us/wdsi/filesubmission). I'll submit the file and hope for the best.

**Comment by yshavit** [comment]
Hm, the file seems to be unmarked as Trojan now. The following works for me:

```
❯ gh release download -R yshavit/mdq v0.4.0 -p mdq-windows.zip

❯ ll
total 1.3M
-rwxrwxrwx 1 yuval yuval 1.3M Mar 26 09:29 mdq-windows.zip

❯ unzip mdq-windows.zip
Archive:  mdq-windows.zip
  inflating: mdq.exe

❯ ll
total 4.6M
-rwxrwxrwx 1 yuval yuval 3.4M Mar 24 21:43 mdq.exe
-rwxrwxrwx 1 yuval yuval 1.3M Mar 26 09:29 mdq-windows.zip

❯ ./mdq.exe --version
mdq 0.4.0
```

Could you provide repro steps for the failure you're seeing?

**Comment by stevehipwell** [comment]
Thanks for the response @yshavit, new versions of Go had a similar problem for a while.

FYI I'm still seeing the failure on my Windows machine on the windows binary but I assume that it's a cached response. If you want to test if the GH runner is blocking the binary the following actions step will work and could be added as part of the post-release process.

```yaml
      - name: Install MDQ
        uses: action-stars/install-tool-from-github-release@ece2623611b240002e0dd73a0d685505733122f6 # v0.2.4
        with:
          github_token: ${{ github.token }}
          owner: yshavit
          repository: mdq
          os_linux: ubuntu
          extract_mode_linux: zip
          extract_mode_macos: zip
          filename_format: "{name}-{os}.{ext}"
          check_command: mdq --version
          version: latest
```
