### ISSUE TITLE
add end-to-end tests

### ISSUE THREAD

**Issue by yshavit** [yshavit/mdq#92]
It'd be cool if I could have a dir that contains yamls, where each yaml is something like:

```yaml
given: |
  <markdown contents>
check:
  - ["# my selector"]: |
    <expected markdown for section>
  - [--some-switch, "[]()"]: |
    <expected markdown for links>
  - ...
```

... and then be able to turn that into a bunch of tests.

This would (a) be useful to have, just for testing; but also (b) be good for documentation of examples.

Ideally, each of those `check` cases would be a separate sub-test; but I think that would require parsing the yaml at compile-time (so that I can use it in a macro), and I don't know if any libraries allow that.

I do think keeping the md and checks in one file (as opposed to something like `test-1.md` + `test-1-check-1.txt`) is useful, because it lets you see the inputs and outputs together more easily.
